### ISSUE TITLE
How did u do it ?

### ISSUE THREAD

**Issue by ghost** [KendallDoesCoding/obfuse-test#1]
Could u tell how did u obfuse it ?

**Comment by KendallDoesCoding** [comment]
Using tools.

Tools -
Obfuse HTML: https://www.wmtips.com/tools/html-obfuscator/#form
Obfuse JS: https://www.preemptive.com/products/jsdefender/online-javascript-obfuscator-demo/

**Comment by ghost** [comment]
> Using tools.
> 
> Tools -
> Obfuse HTML: https://www.wmtips.com/tools/html-obfuscator/#form
> Obfuse JS: https://www.preemptive.com/products/jsdefender/online-javascript-obfuscator-demo/

Thanks I didn't know u could obfuscate html. Have a good day ! 😀

**Comment by KendallDoesCoding** [comment]
> 

I mean, the end result doesn't turn out to HTML, you paste the HTML code and it gives you JS out of it, but the JS does the same thing the HTML code would do, if you see this projects code, you will get an idea of what I'm talking about.

**Comment by ghost** [comment]
> > 
> 
> I mean, the end result doesn't turn out to HTML, you paste the HTML code and it gives you JS out of it, but the JS does the same thing the HTML code would do, if you see this projects code, you will get an idea of what I'm talking about.

Yes ok thanks
